#!/bin/zsh

envjumbox() {
    local jumpbox=""
    if [ "$1" = "prod" ]; then
        jumpbox="dd.prd"
    elif [ "$1" = "staging" ]; then
        jumpbox="dd.stg"
    else
        echo "unkown env '$1'"
        return 1
    fi

    echo "$jumpbox"
}

ipofr() {
    local jumpbox=$(envjumbox "$1")
    
    ssh -tt "$jumpbox" "ssh -G \$(hosts_by_role $2 | head -n 1) | awk '/^hostname/{ print \$2 }'" 2>/dev/null | grep -oP '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -n 1
}

ipofi() {
    local jumpbox=$(envjumbox "$1")
    
    ssh -tt "$jumpbox" "ssh -G $2 | awk '/^hostname/{ print \$2 }'" 2>/dev/null | grep -oP '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -n 1
}

refreshtools(){
    cd ~/.jumpbox-tools
    git pull origin master
    ./installs.sh
    ./links.sh
    cd -
    exec zsh
}
