#!/bin/zsh

# ssh port forwarder to profile go apps

_rprof_usage() {
    echo "rprof is a port forwarder to profile go apps"
    echo "usage: rprof env type target [port]"
    echo ""
    echo "    - env     remote evironment: 'prod' or 'staging'"
    echo "    - type    lookup type: 'a': ip address, 'r': role, 'i': instance id"
    echo "    - target  service running app to profile"
    echo "    - port    specify local tunnel port, default 8080"
}

function rprof() {
    if [ $# -le 3 ]; then
        _rprof_usage
        return 1
    fi

    local ip=""
    if [ "$2" = "a" ]; then
        ip=$3
    elif [ "$2" = "i" ]; then
        ip=$(ipofi "$3")
    elif [ "$2" = "r" ]; then
        ip=$(ipofr "$3")
    else;
        _rprof_usage
        return 1
    fi

    if [ "$ip" = "" ]; then
        return 1
    fi
    shift 3

    local port=8080
    if [ $# -ge 4 ]; then
        port=$4
        shift 1
    fi

    ssh -f -o ExitOnForwardFailure=yes -L "$port":localhost:6060 $ip sleep 1
    echo "ssh tunnel pid $! don't forget to kill it when done"
}
